remove member from cache when ban
mineral-dart/core pull request #180
Opened 2024-08-01 19:26 UTC by PyGaVS

2024-08-01 21:12 UTC, LeadcodeDev requested changes

2024-08-01 21:12 UTC, LeadcodeDev commented on lib/infrastructure/internals/packets/listeners/guild_ban_add_packet.dart
> +    logger.trace('GuildBanAddPacket: ${user.username} was ban in ${server.name}');
You can remove this line

2024-08-01 21:12 UTC, LeadcodeDev commented on lib/.DS_Store
Please remove this file

2024-08-01 21:12 UTC, LeadcodeDev commented on .DS_Store
Please remove this file

2024-08-01 21:14 UTC, PyGaVS commented on lib/infrastructure/internals/packets/listeners/guild_ban_add_packet.dart
> +    logger.trace('GuildBanAddPacket: ${user.username} was ban in ${server.name}');
ok

2024-08-15 14:17 UTC, LeadcodeDev approved these changes

2024-08-15 14:18 UTC, merged