Feat/implement server message methods
mineral-dart/core pull request #183
Opened 2024-08-04 17:31 UTC by LeadcodeDev

2024-08-05 12:53 UTC, vic256 requested changes

2024-08-05 12:53 UTC, vic256 commented on lib/api/server/server_message.dart
> +    }
This could prevent responses in all the other text channels (voice, announcements, threads, etc.) and I don't think this is the desired behaviour. By the way, a message is only supposed to be in a text channel, so we should be able to reply to it, so this test doesn't seem useful.

2024-08-05 12:53 UTC, vic256 commented on lib/api/server/server_message.dart
> +  }
The discord API allows to update embeds so it should be available here.

2024-08-05 12:53 UTC, vic256 commented on lib/api/server/server_message.dart
> +  }
For the update method, you directly send the payload but here you send the contend and the embeds. Shouldn't we keep the same parameters ?

2024-08-05 12:53 UTC, vic256 commented on lib/infrastructure/internals/datastore/parts/server_message_part.dart
> +          .serializeRemote({...response.body, 'guild_id': serverId});
Why the message is serialized two times (here and at the line 54) ?

2024-08-05 12:53 UTC, vic256 commented on lib/infrastructure/internals/datastore/parts/server_message_part.dart
> +      final rawServerMessage = _kernel.marshaller.serializers.message.deserialize(response.body);
At the line 70, it's the message which is deserialized and not the response body, shouldn't be the same here ?

2024-08-08 17:59 UTC, PandaGuerrier approved these changes
Good job, you respected all the requests we ask to you.

2024-08-08 19:03 UTC, vic256 requested changes

2024-08-08 19:03 UTC, vic256 commented on lib/api/server/server_message.dart
> +  }
We should be able to send components in a reply.

2024-08-09 10:57 UTC, vic256 approved these changes

2024-09-09 18:45 UTC, merged