Feat/implement interaction components
mineral-dart/core pull request #189
Opened 2024-08-12 06:32 UTC by LeadcodeDev

2024-08-12 19:24 UTC, PandaGuerrier commented on lib/domains/components/dialog/contexts/private_dialog_context.dart
> +final class PrivateDialogContext implements DialogContext {
Are you sure we can use dialog in private channels ?

2024-08-12 19:32 UTC, LeadcodeDev commented on lib/domains/components/dialog/contexts/private_dialog_context.dart
> +final class PrivateDialogContext implements DialogContext {
Logically, yes, insofar as the `guild_id` property can be `null` and the condition for using dialogs is to respond to an interaction (which can be used privately).

2024-08-12 19:41 UTC, PandaGuerrier requested changes
Nice and cool features, just few things to edit

2024-08-12 19:41 UTC, PandaGuerrier commented on lib/domains/events/buckets/private_bucket.dart
> +  void buttonClick(PrivateButtonClickEventHandler handle) =>
Why you don't do a common event ? (event & private context)

2024-08-12 19:41 UTC, PandaGuerrier commented on lib/domains/events/contracts/private/private_message_create_event.dart
> +  String? get customId;
Why use a customId here ?

2024-08-12 19:41 UTC, PandaGuerrier commented on lib/domains/events/contracts/server/server_button_click_event.dart
> +
Why you don't use a customId here ?

2024-08-12 19:41 UTC, PandaGuerrier commented on lib/infrastructure/internals/datastore/parts/message_part.dart
> +
Why not just do one option here, requesting a MessageType from dev to avoid code repetition.

2024-08-12 19:41 UTC, PandaGuerrier commented on lib/infrastructure/internals/marshaller/cache_key.dart
> +      'channel-$channelId';
Instead of doing that, why not make an object cache?

ex:

cache = {
 'servers': [...],
 'users': [...],
 'channels': [...],
 ...
}

This would make access to the cache easier, and above all we could enlarge this one, without going through strings to get a channel

2024-08-12 19:41 UTC, PandaGuerrier commented on lib/infrastructure/internals/packets/listeners/interactions/dialog_interaction_create_packet.dart
> +            applicationId: Snowflake(message.payload['application_id']),
Why you don't do a factory for this ? it can be more beautiful to see.

2024-08-12 19:41 UTC, PandaGuerrier commented on lib/infrastructure/internals/packets/listeners/interactions/interaction_create_packet.dart
> +    // TODO: Implement global interaction handling
You don't finished !!!

2024-08-12 19:41 UTC, PandaGuerrier commented on lib/infrastructure/internals/packets/listeners/interactions/select_interaction_create_packet.dart
> +            member: await marshaller.dataStore.member.getMember(
Factory ?

2024-08-12 19:41 UTC, PandaGuerrier commented on lib/infrastructure/kernel/mineral_client.dart
> +            final ServerMemberSelectEvent instance => instance.customId,
Why you don't use a abstract class where you surtype here, for having just: 

customId: (instance as SelectEvent) instance.customId

2024-08-12 19:46 UTC, LeadcodeDev commented on lib/domains/events/contracts/private/private_message_create_event.dart
> +  String? get customId;
Because technically the data in the incoming packet is not the same because the execution context is different.

However, it would have been possible to group the two contexts into a single one, but we would still have the problem of generic messages.
```dart
final class ServerMessage extends Message<ServerChannel> {}

abstract interface class SelectContext<T extends Message<Channel>> {
  Snowflake get id;
  Snowflake get applicationId;
  String get token;
  int get version;
  String get customId;
  T get channel;
}
```

The `Message<Channel>` type is different from `ServerChanel`, so autocompletion will not be correct

2024-08-12 19:48 UTC, LeadcodeDev commented on lib/domains/events/contracts/private/private_message_create_event.dart
> +  String? get customId;
If you don't define a `customId`, the event will trigger all interactions of the same type, so you can listen to everything. Adding the `customId` simply allows you to scope the listener.

2024-08-12 19:48 UTC, LeadcodeDev commented on lib/domains/events/contracts/server/server_button_click_event.dart
> +
My mistake, I will correct it.

2024-08-12 19:49 UTC, LeadcodeDev commented on lib/infrastructure/internals/datastore/parts/message_part.dart
> +
Same issue who I have explain below

2024-08-12 19:53 UTC, LeadcodeDev commented on lib/infrastructure/internals/marshaller/cache_key.dart
> +      'channel-$channelId';
Searching deep inside an object involves more calculations.

In the current scheme of things, we simply have a value associated with a key. The key has a structure that allows us to separate the types of data present in the cache.

2024-08-12 19:53 UTC, LeadcodeDev commented on lib/infrastructure/internals/packets/listeners/interactions/dialog_interaction_create_packet.dart
> +            applicationId: Snowflake(message.payload['application_id']),
I can, I will change this

2024-08-12 19:54 UTC, LeadcodeDev commented on lib/infrastructure/internals/packets/listeners/interactions/interaction_create_packet.dart
> +    // TODO: Implement global interaction handling
This is normal because I've deported all the interactions into separate packets. I'm wondering about the relevance of keeping this event.

2024-08-12 19:54 UTC, LeadcodeDev commented on lib/infrastructure/internals/packets/listeners/interactions/select_interaction_create_packet.dart
> +            member: await marshaller.dataStore.member.getMember(
Same, I will change this

2024-08-12 19:54 UTC, PandaGuerrier commented on lib/domains/events/buckets/private_bucket.dart
> +  void buttonClick(PrivateButtonClickEventHandler handle) =>
Okay I see

2024-08-12 19:55 UTC, PandaGuerrier commented on lib/infrastructure/internals/marshaller/cache_key.dart
> +      'channel-$channelId';
Need to talk about this

2024-08-12 19:56 UTC, PandaGuerrier commented on lib/domains/events/contracts/private/private_message_create_event.dart
> +  String? get customId;
Yes but why in privateMessageCreate, it's use any customId ?

2024-08-12 19:57 UTC, PandaGuerrier commented on lib/domains/components/dialog/contexts/private_dialog_context.dart
> +final class PrivateDialogContext implements DialogContext {
Okay 👌🏽

2024-08-12 20:00 UTC, LeadcodeDev commented on lib/infrastructure/kernel/mineral_client.dart
> +            final ServerMemberSelectEvent instance => instance.customId,
I can and I will I think

2024-08-15 14:10 UTC, PandaGuerrier approved these changes

2024-08-15 14:10 UTC, merged