feat: implement events GuildDelete
mineral-dart/core pull request #88
Opened 2023-03-20 03:52 UTC by ThibaultPointurier

2023-03-20 07:11 UTC, LeadcodeDev requested changes

2023-03-20 07:11 UTC, LeadcodeDev commented on lib/src/internal/websockets/events/guild_delete_event.dart
> +  GuildDeleteEvent(this._id);
Could you return the Guild instance instead an id

2023-03-20 07:11 UTC, LeadcodeDev commented on lib/src/internal/websockets/packets/guild_delete_packet.dart
> +      eventService.controller.add(GuildDeleteEvent(guild.id));
Could you give an Guild instance instead Snowflake

2023-03-20 14:52 UTC, LeadcodeDev approved these changes

2023-03-20 15:29 UTC, vic256 approved these changes
I think it's a good idea to set guild not null to avoid some errors in the future. 
However, I approve changes.

2023-03-20 15:29 UTC, vic256 commented on lib/src/internal/websockets/packets/guild_remove_packet.dart
> +    Guild? guild = client.guilds.cache.get(payload['guild_id']);
Normally the guild is present in the cache. Keep a value that can be null here could be a problem as in the event the guild isn't null. Maybe use ``getOrFail`` instead of ``get``.

2023-03-21 23:56 UTC, ThibaultPointurier commented on lib/src/internal/websockets/packets/guild_remove_packet.dart
> +    Guild? guild = client.guilds.cache.get(payload['guild_id']);
The changes we were making

2023-03-22 00:12 UTC, LeadcodeDev approved these changes

2023-03-22 00:13 UTC, merged